# Generated by Django 2.2.3 on 2019-07-15 01:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0002_auto_20190714_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('user', 'date')},
        ),
    ]
