# Generated by Django 2.2.3 on 2019-07-14 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('financial_asset', 'Financial asset'), ('fixed_asset', 'Fixed asset'), ('current_asset', 'Current asset'), ('current_lib', 'Current liability'), ('current_lib', 'Noncurrent liability')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
