# Generated by Django 2.2.3 on 2019-07-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
        ('worth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worth_items', to='statements.Statement'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('financial_asset', 'Financial asset'), ('fixed_asset', 'Fixed asset'), ('current_asset', 'Current asset'), ('current_liab', 'Current liability'), ('noncurrent_liab', 'Noncurrent liability')], max_length=16),
        ),
    ]
